-- История изменений корректировок баланса (для страницы «Все изменения»).
-- Выполнить в Supabase SQL Editor. Скрипт можно запускать повторно.
CREATE TABLE IF NOT EXISTS public.settings_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key text,
  created_at timestamptz DEFAULT now() NOT NULL,
  user_email text,
  comment text
);

CREATE INDEX IF NOT EXISTS settings_history_created_at_idx ON public.settings_history (created_at DESC);
CREATE INDEX IF NOT EXISTS settings_history_setting_key_idx ON public.settings_history (setting_key);

ALTER TABLE public.settings_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read settings_history" ON public.settings_history;
CREATE POLICY "Authenticated can read settings_history"
  ON public.settings_history FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated can insert settings_history" ON public.settings_history;
CREATE POLICY "Authenticated can insert settings_history"
  ON public.settings_history FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Права для роли authenticated (без GRANT insert может молча не писаться)
GRANT SELECT, INSERT ON TABLE public.settings_history TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- Обновить кэш схемы PostgREST, чтобы API сразу видел таблицу
NOTIFY pgrst, 'reload schema';
