-- Поле «Кому» для излишков (как «Кому предоплата»).
-- Выполнить в Supabase SQL Editor. Скрипт можно запускать повторно.

-- 1) Таблица (если ещё не создана)
CREATE TABLE IF NOT EXISTS public.excesses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  client text NOT NULL,
  amount numeric NOT NULL,
  paid_to text,
  created_by text,
  deleted_at timestamptz NULL
);

-- 2) Колонка «Кому» (если таблица уже была без неё)
ALTER TABLE public.excesses
  ADD COLUMN IF NOT EXISTS paid_to text;

-- 3) RLS + политика (идемпотентно)
ALTER TABLE public.excesses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all for authenticated" ON public.excesses;
CREATE POLICY "Allow all for authenticated" ON public.excesses
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
