-- Групповые чаты. Выполнить в Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.group_chats (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_by uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  member_ids uuid[] NOT NULL DEFAULT '{}',
  avatar_storage_path text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_group_chats_member_ids ON public.group_chats USING gin (member_ids);
CREATE INDEX IF NOT EXISTS idx_group_chats_created_at ON public.group_chats (created_at DESC);

CREATE TABLE IF NOT EXISTS public.group_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id uuid NOT NULL REFERENCES public.group_chats (id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  sender_email text NOT NULL DEFAULT '',
  body text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  reply_to_id bigint REFERENCES public.group_messages (id) ON DELETE SET NULL,
  edited_at timestamptz,
  deleted_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_group_messages_chat_created ON public.group_messages (chat_id, created_at);

ALTER TABLE public.group_chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "group_chats_select_member" ON public.group_chats;
CREATE POLICY "group_chats_select_member" ON public.group_chats
  FOR SELECT TO authenticated
  USING (auth.uid() = ANY (member_ids));

DROP POLICY IF EXISTS "group_chats_insert_own" ON public.group_chats;
CREATE POLICY "group_chats_insert_own" ON public.group_chats
  FOR INSERT TO authenticated
  WITH CHECK (created_by = auth.uid() AND auth.uid() = ANY (member_ids));

DROP POLICY IF EXISTS "group_chats_update_member" ON public.group_chats;
CREATE POLICY "group_chats_update_member" ON public.group_chats
  FOR UPDATE TO authenticated
  USING (auth.uid() = ANY (member_ids))
  WITH CHECK (auth.uid() = ANY (member_ids));

DROP POLICY IF EXISTS "group_messages_select_member" ON public.group_messages;
CREATE POLICY "group_messages_select_member" ON public.group_messages
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.group_chats g
      WHERE g.id = group_messages.chat_id
        AND auth.uid() = ANY (g.member_ids)
    )
  );

DROP POLICY IF EXISTS "group_messages_insert_member" ON public.group_messages;
CREATE POLICY "group_messages_insert_member" ON public.group_messages
  FOR INSERT TO authenticated
  WITH CHECK (
    sender_id = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.group_chats g
      WHERE g.id = group_messages.chat_id
        AND auth.uid() = ANY (g.member_ids)
    )
  );

DROP POLICY IF EXISTS "group_messages_update_sender" ON public.group_messages;
CREATE POLICY "group_messages_update_sender" ON public.group_messages
  FOR UPDATE TO authenticated
  USING (sender_id = auth.uid())
  WITH CHECK (sender_id = auth.uid());

-- ---------------------------------------------------------------------------
-- После деплоя API /api/send-group-message-push настройте Database Webhook в Supabase:
--   Table: group_messages
--   Events: INSERT
--   URL: https://ВАШ-ДОМЕН/api/send-group-message-push
--   HTTP Headers: x-push-webhook-secret = значение PUSH_WEBHOOK_SECRET из Vercel
--
-- Участники группы (кроме отправителя) получат Web Push, если включили
-- уведомления на странице «Сообщения» (или в Настройках).
-- ---------------------------------------------------------------------------
