-- История изменений излишков (для страницы «Все изменения»).
-- Выполнить в Supabase SQL Editor. Скрипт можно запускать повторно.
CREATE TABLE IF NOT EXISTS public.excess_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  excess_id bigint REFERENCES public.excesses(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  user_email text,
  comment text
);

CREATE INDEX IF NOT EXISTS excess_history_created_at_idx ON public.excess_history (created_at DESC);
CREATE INDEX IF NOT EXISTS excess_history_excess_id_idx ON public.excess_history (excess_id);

ALTER TABLE public.excess_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read excess_history" ON public.excess_history;
CREATE POLICY "Authenticated can read excess_history"
  ON public.excess_history FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated can insert excess_history" ON public.excess_history;
CREATE POLICY "Authenticated can insert excess_history"
  ON public.excess_history FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Права для роли authenticated (без GRANT insert может молча не писаться)
GRANT SELECT, INSERT ON TABLE public.excess_history TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- Обновить кэш схемы PostgREST, чтобы API сразу видел таблицу
NOTIFY pgrst, 'reload schema';
