-- Задачи по заказам. Выполнить в Supabase SQL Editor.
CREATE TABLE IF NOT EXISTS order_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  author_login text NOT NULL DEFAULT '',
  body text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_order_tasks_order_id ON order_tasks (order_id);

ALTER TABLE order_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for authenticated" ON order_tasks
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
