-- Подписки Web Push (уведомления о задачах для админов и о сообщениях для всех).
-- Выполнить в Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  endpoint text NOT NULL,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, endpoint)
);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_id ON push_subscriptions (user_id);

ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage own push subscriptions" ON push_subscriptions;
CREATE POLICY "Users manage own push subscriptions" ON push_subscriptions
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- После деплоя API /api/send-task-push настройте Database Webhook в Supabase:
--   Table: order_tasks
--   Events: INSERT
--   URL: https://ВАШ-ДОМЕН/api/send-task-push
--   HTTP Headers: x-push-webhook-secret = значение PUSH_WEBHOOK_SECRET из Vercel
--
-- Аналогично для сообщений (user_messages, INSERT):
--   URL: https://ВАШ-ДОМЕН/api/send-message-push
--
-- VAPID-ключи (локально: npx web-push generate-vapid-keys):
--   VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT=mailto:you@example.com
--   PUSH_WEBHOOK_SECRET — произвольная длинная строка
-- ---------------------------------------------------------------------------
