-- История изменений расчётов (для страницы «Все изменения»).
-- Выполнить в Supabase SQL Editor. Скрипт можно запускать повторно.
CREATE TABLE IF NOT EXISTS public.calculation_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calculation_id bigint REFERENCES public.calculations(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  user_email text,
  comment text
);

CREATE INDEX IF NOT EXISTS calculation_history_created_at_idx ON public.calculation_history (created_at DESC);
CREATE INDEX IF NOT EXISTS calculation_history_calculation_id_idx ON public.calculation_history (calculation_id);

ALTER TABLE public.calculation_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read calculation_history" ON public.calculation_history;
CREATE POLICY "Authenticated can read calculation_history"
  ON public.calculation_history FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated can insert calculation_history" ON public.calculation_history;
CREATE POLICY "Authenticated can insert calculation_history"
  ON public.calculation_history FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Права для роли authenticated (без GRANT insert может молча не писаться)
GRANT SELECT, INSERT ON TABLE public.calculation_history TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- Обновить кэш схемы PostgREST, чтобы API сразу видел таблицу
NOTIFY pgrst, 'reload schema';
