-- Таблица «Излишки». Выполнить в Supabase SQL Editor.
CREATE TABLE IF NOT EXISTS excesses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  client text NOT NULL,
  amount numeric NOT NULL,
  paid_to text,
  created_by text,
  deleted_at timestamptz NULL
);

ALTER TABLE excesses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for authenticated" ON excesses
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
