-- Реакции на сообщения (личные и групповые). Выполнить в Supabase → SQL Editor.

CREATE TABLE IF NOT EXISTS public.message_reactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_kind text NOT NULL CHECK (message_kind IN ('user', 'group')),
  message_id bigint NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  emoji text NOT NULL CHECK (char_length(emoji) >= 1 AND char_length(emoji) <= 8),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (message_kind, message_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_message_reactions_message
  ON public.message_reactions (message_kind, message_id);

CREATE INDEX IF NOT EXISTS idx_message_reactions_user
  ON public.message_reactions (user_id, created_at DESC);

COMMENT ON TABLE public.message_reactions IS 'Эмодзи-реакции на сообщения в личных и групповых чатах';
COMMENT ON COLUMN public.message_reactions.message_kind IS 'user = user_messages, group = group_messages';
COMMENT ON COLUMN public.message_reactions.message_id IS 'ID строки в user_messages или group_messages';

ALTER TABLE public.message_reactions ENABLE ROW LEVEL SECURITY;

-- Чтение: участник переписки / группы.
DROP POLICY IF EXISTS "message_reactions_select_participant" ON public.message_reactions;
CREATE POLICY "message_reactions_select_participant" ON public.message_reactions
  FOR SELECT TO authenticated
  USING (
    (
      message_kind = 'user'
      AND EXISTS (
        SELECT 1
        FROM public.user_messages m
        WHERE m.id = message_reactions.message_id
          AND m.deleted_at IS NULL
          AND (m.sender_id = auth.uid() OR m.recipient_id = auth.uid())
      )
    )
    OR (
      message_kind = 'group'
      AND EXISTS (
        SELECT 1
        FROM public.group_messages gm
        JOIN public.group_chats g ON g.id = gm.chat_id
        WHERE gm.id = message_reactions.message_id
          AND gm.deleted_at IS NULL
          AND auth.uid() = ANY (g.member_ids)
      )
    )
  );

-- Добавление / смена своей реакции.
DROP POLICY IF EXISTS "message_reactions_insert_own" ON public.message_reactions;
CREATE POLICY "message_reactions_insert_own" ON public.message_reactions
  FOR INSERT TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND (
      (
        message_kind = 'user'
        AND EXISTS (
          SELECT 1
          FROM public.user_messages m
          WHERE m.id = message_reactions.message_id
            AND m.deleted_at IS NULL
            AND (m.sender_id = auth.uid() OR m.recipient_id = auth.uid())
        )
      )
      OR (
        message_kind = 'group'
        AND EXISTS (
          SELECT 1
          FROM public.group_messages gm
          JOIN public.group_chats g ON g.id = gm.chat_id
          WHERE gm.id = message_reactions.message_id
            AND gm.deleted_at IS NULL
            AND auth.uid() = ANY (g.member_ids)
        )
      )
    )
  );

-- Обновление своей реакции (upsert через ON CONFLICT).
DROP POLICY IF EXISTS "message_reactions_update_own" ON public.message_reactions;
CREATE POLICY "message_reactions_update_own" ON public.message_reactions
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Снятие своей реакции.
DROP POLICY IF EXISTS "message_reactions_delete_own" ON public.message_reactions;
CREATE POLICY "message_reactions_delete_own" ON public.message_reactions
  FOR DELETE TO authenticated
  USING (user_id = auth.uid());
