-- Обмен сообщениями между пользователями. Выполнить в Supabase SQL Editor.

-- Email в profiles для списка пользователей (@-упоминания).
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email text;

UPDATE public.profiles p
SET email = u.email
FROM auth.users u
WHERE p.id = u.id AND (p.email IS NULL OR p.email = '');

CREATE TABLE IF NOT EXISTS public.user_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  recipient_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  sender_email text NOT NULL DEFAULT '',
  recipient_email text NOT NULL DEFAULT '',
  body text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  delivered_at timestamptz,
  read_at timestamptz,
  reply_to_id bigint REFERENCES public.user_messages (id) ON DELETE SET NULL,
  edited_at timestamptz,
  deleted_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_user_messages_created_at ON public.user_messages (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_messages_recipient_unread ON public.user_messages (recipient_id)
  WHERE read_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_user_messages_recipient_undelivered ON public.user_messages (recipient_id)
  WHERE delivered_at IS NULL;

ALTER TABLE public.user_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_messages_select_own" ON public.user_messages;
CREATE POLICY "user_messages_select_own" ON public.user_messages
  FOR SELECT TO authenticated
  USING (sender_id = auth.uid() OR recipient_id = auth.uid());

DROP POLICY IF EXISTS "user_messages_insert_own" ON public.user_messages;
CREATE POLICY "user_messages_insert_own" ON public.user_messages
  FOR INSERT TO authenticated
  WITH CHECK (sender_id = auth.uid());

-- Получатель: read_at / delivered_at; отправитель: правка и мягкое удаление.
DROP POLICY IF EXISTS "user_messages_update_read" ON public.user_messages;
DROP POLICY IF EXISTS "user_messages_update_participants" ON public.user_messages;
CREATE POLICY "user_messages_update_participants" ON public.user_messages
  FOR UPDATE TO authenticated
  USING (sender_id = auth.uid() OR recipient_id = auth.uid())
  WITH CHECK (sender_id = auth.uid() OR recipient_id = auth.uid());

-- Чтение email других пользователей для @-списка (если политики profiles ещё нет).
DROP POLICY IF EXISTS "profiles_select_authenticated" ON public.profiles;
CREATE POLICY "profiles_select_authenticated" ON public.profiles
  FOR SELECT TO authenticated
  USING (true);

-- ---------------------------------------------------------------------------
-- После деплоя API /api/send-message-push настройте Database Webhook в Supabase:
--   Table: user_messages
--   Events: INSERT
--   URL: https://ВАШ-ДОМЕН/api/send-message-push
--   HTTP Headers: x-push-webhook-secret = значение PUSH_WEBHOOK_SECRET из Vercel
--
-- Получатель должен включить уведомления на странице «Сообщения» (или в Настройках).
-- Используются те же VAPID-ключи и таблица push_subscriptions, что и для задач.
--
-- Для мгновенного обновления UI (не только push) выполните supabase_messages_live.sql.
-- ---------------------------------------------------------------------------
