-- История изменений задач (для страницы «Все изменения»).
-- Кто и когда удалил задачу (мягкое удаление).
-- Выполнить в Supabase SQL Editor. Скрипт можно запускать повторно.

CREATE TABLE IF NOT EXISTS public.task_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id bigint REFERENCES public.order_tasks(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  user_email text,
  comment text
);

CREATE INDEX IF NOT EXISTS task_history_created_at_idx ON public.task_history (created_at DESC);
CREATE INDEX IF NOT EXISTS task_history_task_id_idx ON public.task_history (task_id);

ALTER TABLE public.task_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read task_history" ON public.task_history;
CREATE POLICY "Authenticated can read task_history"
  ON public.task_history FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated can insert task_history" ON public.task_history;
CREATE POLICY "Authenticated can insert task_history"
  ON public.task_history FOR INSERT
  TO authenticated
  WITH CHECK (true);

GRANT SELECT, INSERT ON TABLE public.task_history TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

NOTIFY pgrst, 'reload schema';
