-- Сохранённый выбор чекбоксов на странице «Зарплата менеджера».
-- Ключ: manager_salary_unchecked_[<manager>_]YYYY-MM-DD_YYYY-MM-DD (фильтр «Менеджер» + период «с»…«по»)
-- Менеджер по умолчанию (Кристина) пишется без суффикса, Андрей — manager_salary_unchecked_andrey_…
-- Значение: JSON-массив id заказов, снятых с учёта (чекбокс снят), например: ["12","45"]
-- Таблица app_settings уже существует (см. supabase_settings_table.sql); отдельная миграция схемы не нужна.
--
-- Запись в UI разрешена только ролям admin и user (canSaveManagerSalaryChecks в js/roles.js).
-- Пример (опционально):
-- INSERT INTO app_settings (key, value)
--   VALUES ('manager_salary_unchecked_2026-08-01_2026-08-21', '[]')
--   ON CONFLICT (key) DO NOTHING;
