-- Таблица "Расчеты". Выполнить в Supabase SQL Editor.
CREATE TABLE IF NOT EXISTS calculations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  from_place text,
  to_place text,
  amount numeric,
  comment text
);

-- Включить RLS и разрешить доступ по текущей политике (если у вас уже есть политики для orders — добавьте аналогичные для calculations)
ALTER TABLE calculations ENABLE ROW LEVEL SECURITY;

-- Политика: разрешить все операции аутентифицированным пользователям (подстройте под ваши политики)
CREATE POLICY "Allow all for authenticated" ON calculations
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
